package edu.udacity.java.nano.chat;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.springframework.stereotype.Component;

import javax.websocket.*;
import javax.websocket.server.PathParam;
import javax.websocket.server.ServerEndpoint;
import java.io.IOException;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * WebSocket Server
 * @see ServerEndpoint WebSocket Client
 * @see Session   WebSocket Session
 */

@Component
@ServerEndpoint("/chat")
public class WebSocketChatServer {

  /**
   * All chat sessions.
   */
  private static Map<String, Session> onlineSessions = new ConcurrentHashMap<>();

  /**
   * JSON manipulator
   */
  private Gson gson = new Gson();
  private JsonParser jsonParser = new JsonParser();

  /**
   * Distributes the message to all users.
   * Thanks to adtya9876, without whom I probably never would have guessed at "getBasicRemote" as the method for distribution. https://github.com/adtya9876/Chatroom
   * @param message - the Json message to distribute to all users.
   */
  private static void sendMessageToAll(String message) {

    // distribute the content of the msg parameter to all connected clients.
    onlineSessions.forEach((id, session) -> {
      try {
        session.getBasicRemote().sendText(message);
      } catch(IOException e) {
        e.printStackTrace();
      }
    });
  }

  /**
   * Method for distributing online user count when new user enters the room
   * @param session - The new user's session.
   * @param username - The new user's username, entered on the /login screen.
   */
  @OnOpen
  public void onOpen(Session session, @PathParam("username") String username) {

    // add session to onlineSessions map
    onlineSessions.put(session.getId(), session);

    // create new Message object containing the onlineSession size to update all user sessions with the accurate number.
    Message userEnter = new Message( username,"Entering the room: ", "ENTER", onlineSessions.size());

    // send message item with updated count to everyone
    sendMessageToAll(gson.toJson(userEnter));

  }

  /**
   * Method for formatting and distributing a user's message.
   * @param session - The current user's session.
   * @param jsonStr - The JSON-formatted message, received from the UI. Contains username and message text.
   */
  @OnMessage
  public void onMessage(Session session, String jsonStr) {

    // create new Message object from the jsonStr parameter.
    JsonObject json = jsonParser.parse(jsonStr).getAsJsonObject();
    JsonElement jsonElem = gson.toJsonTree(json);

    // add missing message properties
    jsonElem.getAsJsonObject().addProperty("type", "SPEAK");
    jsonElem.getAsJsonObject().addProperty("onlineCount", onlineSessions.size());

    // return the JsonObject to regular JSON and create a Message object from that JSON.
    jsonStr = gson.toJson(jsonElem);
    Message newUserMessage = gson.fromJson(jsonStr, Message.class);

    // distribute message to all
    sendMessageToAll(gson.toJson(newUserMessage));
  }

  /**
   * Method for distributing online user count when a user exits the chatroom.
   * @param session - The exiting user's session.
   * @param username - The exiting user's username.
   */
  @OnClose
  public void onClose(Session session, @PathParam("username") String username) {

    // remove session from onlineSessions map
    onlineSessions.remove(session.getId());

    // create new Message object containing the onlineSession size to update all user sessions with the accurate number.
    Message userLeave = new Message( username,"Leaving the room: ", "LEAVE", onlineSessions.size());

    // send message item with updated count to everyone
    sendMessageToAll(gson.toJson(userLeave));

  }

  /**
   * Exception handler for the chatroom
   * @param session - The current user's session.
   * @param error - The error generated by the user.
   */
  @OnError
  public void onError(Session session, Throwable error) {

    error.printStackTrace();

  }

}
